version: "3"

services:
  fastapi-cdn-api:
    build: ./cdn_api/src/
    env_file:
      - .env
    networks:
      - backend
    expose:
      - "8000"
    depends_on:
      - es
      - redis

  nginx:
    image: nginx:latest
    restart: on-failure
    privileged: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf:ro
      - static_volume:${APP_HOME}/staticfiles
    depends_on:
      - fastapi-content-api
    ports:
      - "80:80"
    networks:
      - backend

volumes:
  postgres-db:
  static_volume:

networks:
  backend:
