@startuml
skinparam componentStyle uml2

actor Moderator
actor Client
component API_upload_object
component API_get_object
database S3

database Cache
component Scheduler


Moderator -right-> API_upload_object: Upload File

API_upload_object -right-> S3: Multipart file\nupload to S3
S3 <-right- API_get_object: Gets File from S3
API_get_object <-right-> Client: Client gets expected file\nfrom the closest location
API_upload_object -down-> Cache: Save information about\nlatest uploaded part to S3
Scheduler <-left-> Cache: Periodically checks\nnon-finished uploads
Scheduler -up-> S3: Upload file to S3,\nUpdate data in database

@enduml