@startuml

==Successful upload==

Moderator -> API_upload_object: Send File

activate API_upload_object
API_upload_object -> S3: Upload File
API_upload_object --> Cache: Save file info and status
deactivate API_upload_object

activate S3

S3 <- API_get_object: Gets File from S3
Cache <- API_get_object: Checks file status
activate API_get_object
API_get_object <-> Client: Client gets expected file
deactivate API_get_object
deactivate S3

@enduml