@startuml

==Start after failure. It works the same for manual file upload and\nCDN(upload from origin node to edge).==

Scheduler <--> redis: Scheduler gets file\ndata from DB
activate redis
activate Scheduler
Scheduler -> redis: Update file status
deactivate redis
Scheduler -> S3: Multipart File Upload
deactivate Scheduler

activate S3

S3 <- API_service_get: Gets File from CDN
activate API_service_get
API_service_get <-> Client: Client gets expected file
deactivate API_service_get
deactivate S3
@enduml